'use client';

import { useEffect, useState } from 'react';
import Link from 'next/link';
import { Home, Search, BookOpen, Zap } from 'lucide-react';
import { PeriodicTable } from '@/components/PeriodicTable';
import { Navigation } from '@/components/Navigation';

export default function HomePage() {
  const [mounted, setMounted] = useState(false);

  useEffect(() => {
    setMounted(true);
  }, []);

  if (!mounted) return null;

  return (
    <main className="min-h-screen">
      <Navigation />

      <div className="relative overflow-hidden">
        <div className="absolute inset-0 bg-gradient-to-r from-purple-500/20 via-transparent to-blue-500/20 blur-3xl -z-10" />

        <div className="container mx-auto px-4 py-20">
          {/* Header */}
          <div className="text-center mb-16">
            <div className="inline-flex items-center gap-2 px-4 py-2 rounded-full bg-blue-500/10 border border-blue-500/30 mb-6">
              <Zap className="w-4 h-4 text-blue-400" />
              <span className="text-sm text-blue-300">Interactive Chemistry Learning</span>
            </div>

            <h1 className="text-5xl md:text-6xl font-bold mb-4 gradient-text">
              Chemistry Explorer
            </h1>

            <p className="text-lg text-slate-300 max-w-2xl mx-auto mb-8">
              Discover the periodic table, explore atomic structures, and learn chemistry
              through interactive 3D models and gamified quizzes powered by AI.
            </p>

            <div className="flex flex-col sm:flex-row gap-4 justify-center mb-12">
              <Link href="#periodic-table" className="btn-primary">
                Explore Elements
              </Link>
              <Link href="/molecules" className="btn-secondary">
                View Molecules
              </Link>
            </div>
          </div>

          {/* Features Grid */}
          <div className="grid md:grid-cols-4 gap-4 mb-16">
            {[
              {
                icon: Home,
                title: 'Periodic Table',
                description: 'Interactive 18-column periodic table with all 118 elements',
              },
              {
                icon: BookOpen,
                title: 'Atomic Structure',
                description: 'Visual representations of nucleus and electron orbits',
              },
              {
                icon: Zap,
                title: 'AI Quizzes',
                description: 'Dynamic quizzes generated by Gemini AI',
              },
              {
                icon: Search,
                title: 'Molecule Search',
                description: '3D molecular structures with interactive visualization',
              },
            ].map((feature, i) => (
              <div key={i} className="card">
                <feature.icon className="w-8 h-8 text-purple-400 mb-3" />
                <h3 className="font-semibold mb-2">{feature.title}</h3>
                <p className="text-sm text-slate-400">{feature.description}</p>
              </div>
            ))}
          </div>

          {/* Periodic Table Section */}
          <div id="periodic-table" className="mb-20">
            <div className="text-center mb-8">
              <h2 className="text-3xl font-bold mb-2">Periodic Table of Elements</h2>
              <p className="text-slate-400">Click on any element to explore its properties</p>
            </div>
            <PeriodicTable />
          </div>

          {/* Quick Navigation Cards */}
          <div className="grid md:grid-cols-3 gap-6">
            <Link
              href="/quiz"
              className="card-hover group"
            >
              <div className="flex justify-between items-start mb-4">
                <div className="text-3xl">🎮</div>
              </div>
              <h3 className="text-xl font-bold mb-2 group-hover:text-purple-300">Quiz Mode</h3>
              <p className="text-slate-400 mb-4">
                Test your knowledge with AI-generated quizzes based on what you're learning.
              </p>
              <div className="text-sm text-purple-400">Start Quiz →</div>
            </Link>

            <Link
              href="/notes"
              className="card-hover group"
            >
              <div className="flex justify-between items-start mb-4">
                <div className="text-3xl">📝</div>
              </div>
              <h3 className="text-xl font-bold mb-2 group-hover:text-purple-300">My Notes</h3>
              <p className="text-slate-400 mb-4">
                Save and organize interesting facts and key concepts from your studies.
              </p>
              <div className="text-sm text-purple-400">View Notes →</div>
            </Link>

            <Link
              href="/molecules"
              className="card-hover group"
            >
              <div className="flex justify-between items-start mb-4">
                <div className="text-3xl">🧬</div>
              </div>
              <h3 className="text-xl font-bold mb-2 group-hover:text-purple-300">Molecules</h3>
              <p className="text-slate-400 mb-4">
                Explore molecular structures in 3D with interactive rotation and details.
              </p>
              <div className="text-sm text-purple-400">Explore Molecules →</div>
            </Link>
          </div>
        </div>
      </div>
    </main>
  );
}
